---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - /external_vars.yml
    
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      name: testvm_2
      state: poweredon
      template: Centos8_G
      disk:
      - size_gb: 20
        type: thin
        datastore: VmLocal
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 2
        scsi: paravirtual
        memory_reservation_lock: True
        mem_limit: 8096
        mem_reservation: 4096
        cpu_limit: 8096
        cpu_reservation: 4096
        max_connections: 5
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
        #version: 18 # Hardware version of virtual machine
        boot_firmware: "efi"
      cdrom:
        type: iso
        iso_path: "[VmLocal] /images/CentOS-8.1.1911-x86_64-dvd1.iso"
      networks:
      - name: VM Network
        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
