---
- hosts: zabbix8
  become: true
  vars_files:
    - creds.yml
  tasks:
    - name: update the system
      yum:
        name: "*"
        state: latest

    - name: register system with redhat 
      shell: |
        sudo subscription-manager register --username davidbennettjr --password Gund@m420
        sudo subscription-manager attach
    -
#    - name: install gnome
#      become: true
#      shell: sudo yum -y groupinstall "GNOME Desktop" "Graphical Administration Tools"

    # - name: set gui as default
    #   become: true
    #   shell: sudo ln -sf /lib/systemd/system/runlevel5.target /etc/systemd/system/default.target     

    - name: install nginx, mysql and php
      become: true
      yum:
        state: present
        name:
          - nginx
          - php
          - mysql-server
          # - mariadb-server
             
    - name: cleaning
      shell: yum clean all
          
    - name: restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for 10 seconds
      pause:
        seconds: 10

    - name: wait for the system to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 120

    - name: update repo cache
      yum:
        update_cache: yes

    - name: Install Zabbix with yum 
      yum: name=https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    
    - name: install zabbix server, frontend, & agent
      become: true
      yum:
        state: present
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent
          - zabbix-nginx-conf
    
    - name: Enable and start mysql
      service: 
        name: mysqld
        enabled: yes
        state: started

    - name: set selinux
      become: true
      shell: |
        setsebool -P nginx_can_network_connect on
        setsebool -P nginx_can_connect_zabbix 1
        setsebool -P httpd_can_network_connect on
        setsebool -P httpd_can_connect_zabbix 1
        setsebool -P zabbix_can_network 1

    - name: cleaning
      shell: yum clean all

      
# c. Create initial database
# documentation

# Run the following on your database host.
# # mysql -uroot -p
# password
# mysql> create database zabbix character set utf8 collate utf8_bin;
# mysql> create user zabbix@localhost identified by 'password';
# mysql> grant all privileges on zabbix.* to zabbix@localhost;
# mysql> quit;

# On Zabbix server host import initial schema and data. You will be prompted to enter your newly created password.
# # zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix
# d. Configure the database for Zabbix server

# Edit file /etc/zabbix/zabbix_server.conf
# DBPassword=password
# e. Configure PHP for Zabbix frontend

# Edit file /etc/nginx/conf.d/zabbix.conf, uncomment and set 'listen' and 'server_name' directives.
# # listen 80;
# # server_name example.com;

# Edit file /etc/php-fpm.d/zabbix.conf, uncomment and set the right timezone for you.
# ; php_value[date.timezone] = Europe/Riga
# f. Start Zabbix server and agent processes

# Start Zabbix server and agent processes and make it start at system boot.
# # systemctl restart zabbix-server zabbix-agent nginx php-fpm
# # systemctl enable zabbix-server zabbix-agent nginx php-fpm 

# disable se linux
# stop zabbix 
#  2.Delete Zabbix database
# DROP DATABASE <Db_name>
# 　3.Create Zabbix database
# CREATE DATABASE <Db_name>
# 　4.Restore the obtained backup
# mysql -u username -p database_name < backup_name.sql
# 　5.Start Zabbix Server 
      