---
- hosts: all
  become: true
  vars_files:
    - creds.yml

  tasks:
    - name: update the system
      dnf:
        name: "*"
        skip_broken: yes
        state: latest
        
    - name: restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for 10 seconds
      pause:
        seconds: 10

    - name: wait for the system to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60

    - name: Install base system req packages 
      become: true
      dnf:
        state: present
        name:
         - lvm2
         - wget 
         - dnf-utils
         - yum-utils              
         - epel-release 
         - curl

    - name: Add Docker GPG apt Key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: add docker repo
      become: true
      shell:
        yum-config-manager \
        --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo

    - name: install containerd.io version 1.2
      become: true
      dnf:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

    - name: update repo cache
      dnf:
        update_cache: yes
    
    - name: install docker
      become: true
      dnf:
        state: present
        name: 
          - docker-ce-cli
          - docker-ce

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Enable and start docker
      service: 
        name: docker
        enabled: yes
        state: started

    - name: pull jenkins image
      docker_image:
        name: jenkins/jenkins
        source: pull

    - name: jenkins Container 
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        state: started
        published_ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - jenkins_data:/jenkins_config
          - jenkins_data:/var/Jenkins_home
        restart_policy: always
                
    - name: Allow docker traffic
      firewalld:
        zone: trusted
        interface: docker0
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
