---
- hosts: blackflag,plexservers
  become: true
  vars_files:
    - creds.yml
  tasks:
  
    - name: Install Zabbix with yum 
      shell: |
        wget https://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-2+bionic_all.deb
        dpkg -i zabbix-release_3.0-2+bionic_all.deb
        apt update 
        firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="zabbix_server_ip_address/32" port protocol="tcp" port="10050" accept'
      #https://repo.zabbix.com/zabbix/3.0/rhel/8/x86_64/zabbix-release-3.0-4.el8.noarch.rpm

    - name: install zabbix agent
      become: true
      apt:
        state: present
        name:
          #- zabbix
          - zabbix-agent

    - name: Enable and start mariadb
      service: 
        name: zabbix-agent
        enabled: yes
        state: started 
    
    # - name: set selinux
    #   become: true
    #   shell: |
    #     setsebool -P httpd_can_network_connect on
    #     setsebool -P httpd_can_connect_zabbix 1
    #     setsebool -P zabbix_can_network 1

   