---
- hosts: blackflag
  become: true
  vars_files:
    - creds.yml
  tasks:
    - name: update the system
      apt:
        name: "*"
        state: latest
        
    - name: restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for 10 seconds
      pause:
        seconds: 10

    - name: wait for the system to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 120
    
    - name: install nordvpn client package
      apt:
        deb: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
        

    - name: update repo cache
      apt:
        update_cache: yes

    - name: Install base system req packages 
      become: true
      apt:
        state: present
        name:
         - apt-transport-https 
         - ca-certificates 
         - curl 
         - gnupg-agent 
         - software-properties-common
         - python3-pip
         - docker.io
         - nordvpn
        #  - firewalld
        #  - iptables

    - name: Install Docker Module for Python
      pip:
        name: 
         - docker
         - docker-compose

    # - name: Disable and stop ufw
    #   service: 
    #     name: ufw
    #     enabled: no
    #     state: stopped

    - name: Enable and start docker
      service: 
        name: docker
        enabled: yes
        state: started

    - name: run the mediaservers docker-compose.yml
      docker_compose:
        project_name: media-server
        definition:
          version: "3"
          services:
            transmission:
              image: linuxserver/transmission
              container_name: transmission
              restart: always
              privileged: true
              ports:
                - "9091:9091"
                - "51413:51413"
                - "51413:51413/udp"
              networks:
                - plexnet
              environment:
                - PUID=1000
                - PGID=1000
                - USER:=me
                - PASS:=me
              volumes:
                - /home/falcon/data:/config
                - /home/falcon/Downloads:/downloads
                - /home/falcon/watch:/watch
              restart: unless-stopped
            radarr:
              image: linuxserver/radarr
              container_name: radarr
              restart: always
              ports:
                - "7878:7878"
              networks:
                - plexnet
              environment:
                - PGID=1000
                - PUID=1000
                - TZ=America/New_York
              volumes:
                - /home/falcon/Downloads:/home/downloads
                - /home/falcon/Videos:/home/movies
                - /home/falcon/radarr:/home/config
              restart: unless-stopped
            sonarr:
              image: linuxserver/sonarr
              container_name: sonarr
              restart: always
              ports:
                - "8989:8989"
              networks:
                - plexnet
              environment:
                - PGID=1000
                - PUID=1000
                - TZ=America/New_York
              volumes:
                - /home/falcon/Downloads:/home/downloads
                - /home/falcon/Videos:/home/videos
                - /home/falcon/sonarr-config:/sonarr/config
                #- ${MOUNT_POINT}/transmission:/data
              restart: unless-stopped
            jackett:
              image: linuxserver/jackett
              container_name: jackett
              restart: always
              networks:
                - plexnet
              environment:
                - PGID=1000
                - PUID=1000
                - TZ=America/New_York
              volumes:
                - /home/falcon/jackett-config:/config
                - /home/falcon/jacket-downloads:/downloads
              ports:
                - "9117:9117"
              restart: unless-stopped
            # emby: I switched to plex on seperate compute node
            #   image: emby/embyserver
            #   environment:
            #     - UID=1000
            #     - GID=100
            #     - GIDLIST=100,44
            #   devices:
            #     - /dev/dri/renderD128
            #   volumes:
            #     - ${MOUNT_POINT}/emby/config:/config
            #     - ${MOUNT_POINT}/media/movies:/movies
            #     - ${MOUNT_POINT}/media/tv:/tv
            #   ports:
            #     - 8096:8096
            #     - 8920:8920
            #   restart: unless-stopped
            # bazarr: switched to plex (plex subtitle api thing)
            #   build: docker-bazarr
            #   container_name: bazarr
            #   environment:
            #     - PUID=1001
            #     - PGID=1001
            #     - TZ=America/New_York
            #   volumes:
            #     - ${MOUNT_POINT}/bazarr/config:/config
            #     - ${MOUNT_POINT}/media/movies:/movies
            #     - ${MOUNT_POINT}/media/tv:/tv
            #   ports:
            #     - 6767:6767
            #   deploy:
            #     resources:
            #       limits:
            #         memory: 4096M
            #   restart: unless-stopped
          networks:
            plexnet:
              driver: bridge

    